### ISSUE TITLE
Change link type with plugin wis2box.data.universal.UniversalData

### ISSUE THREAD

**Issue by davidpodeur** [World-Meteorological-Organization/wis2box#894]
Hi,

For data published using wis2box.data.universal.UniversalData, we get data links announced with **"type": "application/octet-stream"**, when it would be expected to be **"application/bufr"**

Example of data notification:

```
[rocky@vps-1b403fa7 ~]$ mosquitto_sub -h globalbroker.meteo.fr -p 1883 -t origin/a/wis2/fr-meteofrance/# -u everyone -P everyone -C 1F "[{\"topic\": \"%t\"},%p]" | python3 -m json.tool
[
    {
        "topic": "origin/a/wis2/fr-meteofrance/data/core/weather/space-based-observations/noaa-18/amsu-a"
    },
    {
        "id": "2afad26d-43a5-419a-a286-dbca2565934d",
        "type": "Feature",
        "conformsTo": [
            "http://wis.wmo.int/spec/wnm/1/conf/core"
        ],
        "geometry": null,
        "properties": {
            "data_id": "fr-meteofrance:dbnet-noaa-18-amsu-a/INAD03_LFPW_181331.da03bfcc256be24363013b3156c5d8ab_20250318",
            "datetime": "2025-03-18T00:00:00Z",
            "pubtime": "2025-03-18T13:33:02Z",
            "integrity": {
                "method": "sha512",
                "value": "uTzV3tQex6ZPOJQC/mlG7DIHSyXFyxSiT0PyfVcCXood9gCaGr8HCXZ9hbr29zm6OZOaiCsR25Rnc3DoUExiDQ=="
            },
            "metadata_id": "urn:wmo:md:fr-meteofrance:dbnet-noaa-18-amsu-a"
        },
        "links": [
            {
                "rel": "canonical",
                **"type": "application/octet-stream",**
                "href": "https://wis2nc.meteo.fr/data/2025-03-18/wis/urn:wmo:md:fr-meteofrance:dbnet-noaa-18-amsu-a/INAD03_LFPW_181331.da03bfcc256be24363013b3156c5d8ab_20250318.bufr",
                "length": 149411
            }
        ],
        "generated_by": "wis2box 1.0.0rc1"
    }
]
```

Corresponding dataset definition file:

```
wis2box@wis2node-fr-int:~$ cat ./wis2box-data/datasets/dbnet/dataset-dbnet-template.yml-noaa-18-amsu-a
wis2box:
  retention: P30D
  topic_hierarchy: fr-meteofrance.data.core.weather.space-based-observations.noaa-18.amsu-a
  centre_id: fr-meteofrance
  data_mappings:
    plugins:
      bufr:
      - plugin: wis2box.data.universal.UniversalData
        notify: true
        file-pattern: "^.*?_(\\d{8}).*?\\..*$"

mcf:
    version: 1.0

metadata:
    identifier: urn:wmo:md:fr-meteofrance:dbnet-noaa-18-amsu-a
    language: en
    charset: utf8
    hierarchylevel: dataset

identification:
    language: en
    charset: utf8
    title:  DBNET-noaa-18-amsu-a Data (fr-meteofrance)
    abstract: DBNET-noaa-18-amsu-a Data (fr-meteofrance)
    dates:
        creation: 2025-03-01
        publication: 2025-03-01
    keywords:
        default:
            keywords:
                - surface
                - land
                - observations
        wmo:
            keywords:
                - weather
            keywords_type: theme
            vocabulary:
                name: WMO WIS2 Topic Hierarchy
                url: https://github.com/wmo-im/wis2-topic-hierarchy/blob/main/topic-hierarchy/earth-system-discipline/index.csv
    extents:
        spatial:
            - bbox: [-170,-79,179,79]
              crs: 4326
        temporal:
            - begin: 2025-03-01
              end: 2099-12-31
              resolution: P1H
    wmo_data_policy: core

contact:
    host:
        organization: Meteo France
        url: https://www.meteofrance.com
        individualname: David Podeur
        positionname: GISC Toulouse Focal Point
        phone: null
        fax: null
        address: 42 avenue Corolis
        city: Toulouse
        administrativearea: null
        postalcode: '31100'
        country: France
        email: david.podeur@meteo.fr
        hoursofservice: 0700h - 1500h UTC
        contactinstructions: email
```

Is the link type change achievable ?

David
